name: "Build"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - uses: cachix/cachix-action@v12
      with:
        name: grenewode
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --print-build-logs
    - uses: actions/upload-artifact@v3
      with:
        name: proxmox-lxc-container
        path: result/tarball/*
